/**
 * Matches profiles created by auth trigger: coalesce(meta nickname, 'Swimmer' || substr(id::text, 1, 4)).
 * Until this shape, Wardrobe may set the player's first real public nickname.
 */
export function isAutoGeneratedLobbyNickname(n: string): boolean {
  return /^Swimmer[a-f0-9]{4}$/i.test(n.trim());
}
